package org.variantsync.diffdetective.analysis.strategies;

/**
 * Collects all linegraph representations generated by an analysis and exports them at the end.
 * @author Paul Bittner
 */
public class AnalyzeAllThenExport extends AnalyzeAndExportIncrementally {
    public AnalyzeAllThenExport() {
        super(Integer.MAX_VALUE);
    }
}
