name:                proofs
version:             0.1.0.0
github:              "githubuser/proofs"
license:             LGPL-3.0
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/proofs#readme>

dependencies:
- base >= 4.7 && < 5
# - data-ordlist >= 0.4.7.0
- containers >= 0.6.5.1
- mtl >= 2.2.2

library:
  source-dirs:
    - src

executables:
  proofs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proofs

tests:
  proofs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proofs
